POST http://localhost:3000/api/photos HTTP/1.1
Content-Type: multipart/form-data; boundary=----FormBoundary1234

------FormBoundary1234
Content-Disposition: form-data; name="file"; filename="input.jpg"
Content-Type: image/jpeg

< ./input.jpg

------FormBoundary1234
Content-Disposition: form-data; name="album"
Content-Type: text/plain

album1
------FormBoundary1234

########

PATCH http://localhost:3000/api/filters HTTP/1.1
Content-Disposition: form-data; name="data"
Content-Type: application/json

{
  "id": 1686797398655,
  "filters": ["flip", "flop"],
  "tint": {
    "r": 255,
    "g": 0, 
    "b": 0
    }
}


#########

GET http://localhost:3000/api/filters/metadata/1686248945276 HTTP/1.1

####

PATCH http://localhost:3000/api/filters HTTP/1.1
Content-Disposition: form-data; name="data"
Content-Type: application/json

{
  "id": 1686701361786,
  "filterType": "flip",
  "dimensions": {
    "width":230,
    "height": 288
  },
  "tint": {
    "r": 255,
    "g": 0, 
    "b": 0
    }
}

###

PATCH http://localhost:3000/api/filters HTTP/1.1
Content-Disposition: form-data; name="data"
Content-Type: application/json

{
  "id": 1686701361786,
  "filterType": "tint",
  "dimensions": {
    "width":230,
    "height": 288
  },
  "tint": {
    "r": 255,
    "g": 0, 
    "b": 0
    }
}

